# Generated by Django 3.1 on 2021-01-21 12:28

from django.db import migrations, models
import server.constants


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_auto_20210121_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts2pstransfer',
            name='sub_type',
            field=models.IntegerField(choices=[(server.constants.TransferType['TS2PS'], 'TS to PS (Single Degree)'), (server.constants.TransferType['PSTS2PSPS'], 'PS-TS to PS-PS (Dual Degree)'), (server.constants.TransferType['TSTS2TSPS'], 'TS-TS to TS-PS (Dual Degree)')]),
        ),
    ]
