# Generated by Django 3.1 on 2021-01-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_deadlinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('campus', models.IntegerField(blank=True, choices=[(0, 'Goa'), (1, 'Hyderabad'), (2, 'Pilani')], null=True)),
                ('contact', models.CharField(blank=True, help_text='Enter 10 digit contact number', max_length=20, null=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(0, 'Student'), (1, 'Supervisor'), (2, 'Head of Department'), (3, 'Associate Dean'), (4, 'PS-Division')], null=True)),
                ('cgpa', models.CharField(default='NA', max_length=6)),
                ('is_active_tms', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ps2tstransfer',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tms.activeuserprofile'),
        ),
        migrations.AlterField(
            model_name='ts2pstransfer',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tms.activeuserprofile'),
        ),
    ]
