# Generated by Django 3.1 on 2021-01-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_auto_20210121_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuserprofile',
            name='is_active_tms',
            field=models.BooleanField(default=False),
        ),
    ]
