# Generated by Django 3.1 on 2021-01-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
