# Generated by Django 3.1 on 2021-01-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210121_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('campus', models.IntegerField(blank=True, choices=[(0, 'Goa'), (1, 'Hyderabad'), (2, 'Pilani')], null=True)),
                ('contact', models.CharField(blank=True, help_text='Enter 10 digit contact number', max_length=20, null=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(0, 'Student'), (1, 'Supervisor'), (2, 'Head of Department'), (3, 'Associate Dean'), (4, 'PS-Division')], null=True)),
            ],
        ),
    ]
