# Generated by Django 3.1 on 2021-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210121_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active_cms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_psdiary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_tms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
