# Generated by Django 3.1 on 2021-01-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_auto_20210121_1423'),
        ('accounts', '0006_auto_20210121_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
